import type { NextPage } from "next"
import Head from "next/head"

const Home: NextPage = () => {
  const arr = ["a", "b", "c"]

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header></header>

      <main>
        {arr.map(v => (
          <div key={v} className='text-200px'>
            {v}
          </div>
        ))}
      </main>

      <footer></footer>
    </>
  )
}

export default Home
